# Generated by Django 5.0.6 on 2024-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('items', models.TextField()),
            ],
        ),
    ]
