# Generated by Django 5.0.6 on 2024-06-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='prices',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
